kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-services-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-services
subjects:
  - kind: ServiceAccount
    namespace: default
    name: {{ include "kubesquid-ingress-supervisor.serviceAccountName" . }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-kubesquid-configmap-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-kubesquid-configmap
subjects:
  - kind: ServiceAccount
    namespace: default
    name: {{ include "kubesquid-ingress-supervisor.serviceAccountName" . }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-ingresses-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-ingresses
subjects:
  - kind: ServiceAccount
    namespace: default
    name: {{ include "kubesquid-ingress-supervisor.serviceAccountName" . }}
