kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: list-namespaces-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-namespaces
subjects:
  - kind: ServiceAccount
    namespace: default
    name: {{ include "kubesquid-ingress-supervisor.serviceAccountName" . }}
   