kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-services
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["services"]
    verbs: ["watch", "get"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-kubesquid-configmap
  namespace: default
rules:
  - apiGroups: ["*"]
    resourceNames: ["kubesquid"]
    resources: ["configmaps"]
    verbs: ["watch", "get"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-ingresses
  namespace: default
rules:
  - apiGroups: [ "*" ]
    resources: [ "ingresses" ]
    verbs: [ "list", "create", "update", "delete" ]
