# Default values for kubesquid-ingress-supervisor.
replicaCount: 1

image:
  repository: miledevies/kubesquid-ingress-supervisor
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets:
  - name: registry-secret

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
      - NET_RAW
      - CAP_SYS
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}
