image:
  repository: miledevies/kubesquid-ingress-supervisor:3
imagePullSecrets:
  - name: registry-secret
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
replicaCount: 1
