name: pr validation
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ingress-supervisor/Dockerfile
