name: pr validation
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ingress-supervisor/Dockerfile
      - run: |
          IMAGE_NAME=ingress-supervisor-${{ github.event.number }}
          docker build -f ingress-supervisor/Dockerfile -t ${IMAGE_NAME} ingress-supervisor
          docker save --output ${IMAGE_NAME}.tar ${IMAGE_NAME} 
          gzip -c ${IMAGE_NAME}.tar > ${IMAGE_NAME}.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: ingress-supervisor.tar.gz
          path: ingress-supervisor-${{ github.event.number }}.tar.gz

  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ingress-supervisor
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kubesquid-ingress-supervisor:${{ github.event.number }}
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test

  e2e-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
      - uses: actions/checkout@v2
      - uses: helm/kind-action@v1.2.0
        with:
          config: tests/cluster-config.yml
          cluster_name: kind
      - run: ./e2e-test.sh
