name: push latest tag
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  IMAGE_NAME: ingress-supervisor-${{ github.event.number }}

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME }}.tar.gz
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker image load --input ${{ env.IMAGE_NAME }}.tar.gz
          docker image tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/kubesquid-ingress-supervisor:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kubesquid-ingress-supervisor:latest
