name: Release Chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/kubesquid-ingress-supervisor/Chart.yaml'

jobs:
  publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: closed
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kubesquid-ingress-supervisor:${PR}
          docker image tag ${{ secrets.DOCKERHUB_USERNAME }}/kubesquid-ingress-supervisor:${PR} ${{ secrets.DOCKERHUB_USERNAME }}/kubesquid-ingress-supervisor:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kubesquid-ingress-supervisor:latest
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

  release:
    runs-on: ubuntu-latest
    needs: publish-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - run: |
          mkdir .deploys
          helm package charts/kubesquid-ingress-supervisor -d .deploys
      - uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_PACKAGE_PATH: ".deploys"

